### ISSUE TITLE
messages: time positioning is off for video

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#2334]
<img width="368" alt="Screen Shot 2023-01-30 at 9 01 42 AM" src="https://user-images.githubusercontent.com/6990215/215513203-7f9b9bfd-36f5-409f-9412-dc6c1228225d.png">

**Comment by irffanasiff** [comment]
done

**Comment by hkirat** [comment]
I think the issue here is the video has a weird aspect ratio and there's an empty patch at the top, we should probably default to a `black` background for videos

**Comment by hkirat** [comment]
cc @irffanasiff in case you're working on it. Still seeing this in master 
<img width="543" alt="Screenshot 2023-01-31 at 11 47 26 AM" src="https://user-images.githubusercontent.com/8079861/215681707-681007bf-fe6c-4732-9df6-0eee035ac490.png">

**Comment by hkirat** [comment]
@irffanasiff this might still be an issue in master
Check this message by monkey in the `backpack chat`  for recreating this locally
<img width="405" alt="Screenshot 2023-01-31 at 11 53 02 AM" src="https://user-images.githubusercontent.com/8079861/215682720-cdd19cf8-3fb1-4abd-9a5f-c3e9a514ba26.png">

**Comment by irffanasiff** [comment]
<img width="379" alt="Screenshot 2023-01-31 at 12 31 11 PM" src="https://user-images.githubusercontent.com/74172466/215689597-ded41a07-7062-4cc2-9260-5124dc1755f6.png">

**Comment by hkirat** [comment]
I think you're looking at it on a wide enough window.
Check the video on how it behaves as you resize the window. The thing on the left is what should shrink and not the timestamp
https://user-images.githubusercontent.com/8079861/215698957-15f3f581-0448-45c1-9269-a1499e1968d1.mp4

**Comment by hackpk** [comment]
@hkirat  Can I work on this of it is still open??

**Comment by hkirat** [comment]
Go for it @hackpk

**Comment by hackpk** [comment]
okay thanks

**Comment by hackpk** [comment]
https://user-images.githubusercontent.com/22720175/235720910-2959316d-1d46-4f94-89f8-578b2f9c73dc.mp4

the timestamp is working for me. Is there anything else i need to check??
